### ISSUE TITLE
JOSS Review Comments - Reviewer 1

### ISSUE THREAD

**Issue by amkrajewski** [amkrajewski/nimCSO#2]
Below are initial (itemized) JOSS review comments from @Henrium. I will progressively work on addressing them one-by-one here.

1. I have tested in both GitHub Codespaces and Linux, the package is easy to install and works as claimed. 

2. Summary: I suggest the following to make it more accessible to "diverse, non-specialist audience": (1) introduce the background first, then what `nimCSO` is and what it does; (2) elaborate on the purpose and challenges.

3. State of field: What are some other approaches to compositional space optimization; are there relevant software? References should be added if applicable. It's not necessary to compare with them, but good to make the paper informative.

4. In `quickstart.ipynb`: the routine mostCommon is clear at first, but got confusing when it comes to "removing elements". What's the optimization objective of removing elements?

5. The "Algorithm-Based Search" method relies on an assumption, "elements present in already expanded ...", is it supported by any rationale, experiments, prior studies, etc.?

6.  I didn't find "community guidelines", though it doesn't seem necessary here. Consider adding one?

**Comment by RMeli** [comment]
https://github.com/openjournals/joss-reviews/issues/6731

**Comment by RMeli** [comment]
@amkrajewski could you please briefly summarise the progress on the items listed here? Thank you.

**Comment by amkrajewski** [comment]
- [ ] Improvement of the summary to make it more approachable to the general audience.
- [ ] Elaborate on other methods - reference the Python and NumPy implementations presented within the `benchmarks` directory.
- [ ] Add more references to other scientific domains to broadly present the problem.
- [ ] Clarify "removal of elements" in the quick start guide.
- [ ] Elaborate on the rationale for algorithm assumption.
- [ ] Add "community guidelines" on how to contribute and what.

**Comment by amkrajewski** [comment]
Hi @Henrium, thanks again for taking the time and effort to provide valuable feedback. I finished working through all reviewer comments, and I believe the code/paper is ready for you to evaluate my adjustments. 

Notes:
- Above, please find the itemized list of changes I made (some overlapped with https://github.com/amkrajewski/nimCSO/issues/3). 
- In some cases, I wanted to be more verbose, but the paper was already above the recommended length.
- I am happy to make further adjustments.

**Comment by Henrium** [comment]
Hi @amkrajewski, thanks for your comprehensive response to my reviews. My concerns are well addressed, and I think the paper is in good shape @RMeli.

**Comment by RMeli** [comment]
Thanks @Henrium. @amkrajewski, I think we can close the issues then.

@Henrium, would you mind looking at your checklist in https://github.com/openjournals/joss-reviews/issues/6731#issuecomment-2099348790 and see if there are still outstanding items to be addressed? Many thanks!

**Comment by Henrium** [comment]
Thanks for the reminder, all items have been addressed. I've updated the
checklist.

**Comment by amkrajewski** [comment]
@Henrium Again, thank you for your time and effort in the review. I will close this issue as completed.
